"""One-command frontend configuration after a `sam deploy`.

Reads the deployed stack's CloudFormation outputs and writes
`frontend/.env` with the deployed API endpoint — the only build-time
value the frontend needs (sign-in config is fetched at runtime from
GET /config, so a fresh clone needs nothing else).

    python scripts/deploy_and_configure.py [--stack-name NAME] [--region us-east-1]

Defaults: the standard stack name and the region the session
credentials resolve to. Never hardcodes an account id, region or URL;
everything comes from the stack's own outputs.
"""

import argparse
import boto3

STACK_NAME = "intelligent-storage-cost-optimizer"

# The single output key the frontend consumes at build time
# (frontend/.env.example documents why the others are not needed).
REQUIRED_OUTPUT = "DocumentsApiEndpoint"


def collect_outputs(stack_name, region):
    """Stack outputs as {OutputKey: OutputValue}, failing loudly if
    the stack or the one required output is missing."""
    cfn = boto3.client("cloudformation", region_name=region)
    response = cfn.describe_stacks(StackName=stack_name)
    outputs = response["Stacks"][0].get("Outputs", [])
    mapping = {o["OutputKey"]: o["OutputValue"] for o in outputs}

    if REQUIRED_OUTPUT not in mapping:
        raise SystemExit(
            f"Stack '{stack_name}' has no '{REQUIRED_OUTPUT}' output — "
            "this script expects a deployed StorageLens stack."
        )
    return mapping


def render_env(mapping):
    return (
        "# Generated by scripts/deploy_and_configure.py — regenerating\n"
        "# overwrites this file; edits here are not preserved.\n"
        f"VITE_API_BASE_URL={mapping[REQUIRED_OUTPUT]}\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Write frontend/.env from the deployed stack's outputs."
    )
    parser.add_argument("--stack-name", default=STACK_NAME)
    parser.add_argument("--region", default=None)
    args = parser.parse_args()

    if not args.region:
        args.region = boto3.session.Session().region_name

    mapping = collect_outputs(args.stack_name, args.region)

    from pathlib import Path

    env_path = Path(__file__).resolve().parents[1] / "frontend" / ".env"
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(render_env(mapping), encoding="utf-8")

    print(f"Wrote {env_path}")
    print(f"  {REQUIRED_OUTPUT} = {mapping[REQUIRED_OUTPUT]}")
    print("Next: `npm run dev` in frontend/ (or `npm run build`).")


if __name__ == "__main__":
    main()