"""
Load the synthetic live-pipeline dataset into a deployed stack.

Prerequisites:
    python scripts/generate_synthetic_data.py   (already run)
    The CloudFormation/SAM stack must already be deployed.

What it does:
    1. Resolves resource names from the stack's outputs
       (DocumentsBucketName, DocumentsTableName,
       AccessHistoryTableName, DocumentAggregatesTableName) —
       nothing is hard-coded.
    2. Uploads one small deterministic synthetic file per
       document to the S3 documents bucket.
    3. Batch-writes document metadata to DocumentsTable.
    4. Batch-writes DOWNLOAD access events to AccessHistoryTable.

Usage:
    python scripts/load_synthetic_data.py
        [--stack-name intelligent-storage-cost-optimizer]
        [--region ap-south-1]
        [--limit N]          load only the first N documents
        [--skip-s3]          skip the S3 payload uploads
"""

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

DOCUMENTS_FILE = REPO_ROOT / "data" / "synthetic" / "documents_500.json"
EVENTS_FILE = REPO_ROOT / "data" / "synthetic" / "access_events_500.json"


def build_synthetic_payload(document):
    """
    Deterministic small text payload for one synthetic document.
    The content itself does not matter to the optimizer; only
    the S3 object exists and is downloadable.
    """

    lines = [
        "SYNTHETIC TEST DOCUMENT (no real personal data)",
        f"document_id: {document['document_id']}",
        f"file_name: {document['file_name']}",
        f"practice_area: {document['practice_area']}",
        f"owner: {document['owner']}",
        f"current_storage_class: {document['current_storage_class']}",
    ]

    return "\n".join(lines)


def resolve_stack_resources(stack_name, region):
    """
    Resolve the deployed resource names from CloudFormation.
    Bucket and table names are generated by CloudFormation and
    must never be hard-coded.

    Preferred source is the stack Outputs (AccessHistoryTableName
    was added to the template); for stacks deployed before that
    output existed, fall back to the stack resource list.
    """

    import boto3

    cfn = boto3.client("cloudformation", region_name=region)

    stacks = cfn.describe_stacks(
        StackName=stack_name
    ).get("Stacks", [])

    if not stacks:
        raise RuntimeError(
            f"Stack not found: {stack_name}"
        )

    outputs = {
        output["OutputKey"]: output["OutputValue"]
        for output in stacks[0].get("Outputs", [])
    }

    documents_bucket = outputs.get("DocumentsBucketName")
    documents_table = outputs.get("DocumentsTableName")
    aggregates_table = outputs.get("DocumentAggregatesTableName")
    access_history_table = outputs.get("AccessHistoryTableName")

    if not access_history_table:
        resources = cfn.list_stack_resources(
            StackName=stack_name
        ).get("StackResourceSummaries", [])

        access_history_table = next(
            (
                resource["PhysicalResourceId"]
                for resource in resources
                if resource["LogicalResourceId"] == "AccessHistoryTable"
            ),
            None,
        )

    for name, value in [
        ("DocumentsBucketName", documents_bucket),
        ("DocumentsTableName", documents_table),
    ]:
        if not value:
            raise RuntimeError(
                f"Stack output {name} not found — "
                "is the stack deployed?"
            )

    if not access_history_table:
        raise RuntimeError(
            "AccessHistoryTable resource not found in stack."
        )

    return {
        "bucket": documents_bucket,
        "documents_table": documents_table,
        "access_history_table": access_history_table,
        "aggregates_table": aggregates_table,
    }


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Load the synthetic dataset into the deployed stack."
        )
    )

    parser.add_argument(
        "--stack-name",
        default="intelligent-storage-cost-optimizer",
    )

    parser.add_argument(
        "--region",
        default="ap-south-1",
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Load only the first N documents.",
    )

    parser.add_argument(
        "--skip-s3",
        action="store_true",
        help="Skip S3 payload uploads (metadata/events only).",
    )

    parser.add_argument(
        "--purge-access-history",
        action="store_true",
        help=(
            "Delete all existing events in AccessHistoryTable "
            "before writing, so re-seeding cannot double-count."
        ),
    )

    args = parser.parse_args()

    import boto3

    documents_raw = json.loads(
        DOCUMENTS_FILE.read_text(encoding="utf-8")
    )
    events_raw = json.loads(
        EVENTS_FILE.read_text(encoding="utf-8")
    )

    documents = documents_raw["documents"]

    if args.limit:
        documents = documents[: args.limit]

        limited_ids = {
            document["document_id"]
            for document in documents
        }

        events = [
            event
            for event in events_raw["events"]
            if event["document_id"] in limited_ids
        ]
    else:
        events = events_raw["events"]

    print(f"Stack:   {args.stack_name}")
    print(f"Region:  {args.region}")

    resources = resolve_stack_resources(
        args.stack_name,
        args.region,
    )

    print(f"Bucket:  {resources['bucket']}")
    print(
        f"Tables:  {resources['documents_table']}, "
        f"{resources['access_history_table']}"
    )

    s3 = boto3.client("s3", region_name=args.region)
    dynamodb = boto3.resource(
        "dynamodb", region_name=args.region
    )

    documents_table = dynamodb.Table(
        resources["documents_table"]
    )
    access_history_table = dynamodb.Table(
        resources["access_history_table"]
    )

    if args.purge_access_history:
        deleted = 0

        print("Purging existing access-history events ...")

        # Restart the scan from the beginning after each page of
        # deletions; deletion is monotonic, so the scan shrinks
        # each round until it is empty.
        while True:
            old_events = access_history_table.scan().get(
                "Items", []
            )

            if not old_events:
                break

            keys = [
                {
                    "document_id": event["document_id"],
                    "access_timestamp": event["access_timestamp"],
                }
                for event in old_events
            ]

            with access_history_table.batch_writer() as batch:
                for key in keys:
                    batch.delete_item(Key=key)

            deleted += len(keys)

        print(f"Purged {deleted} existing events.")

    if not args.skip_s3:
        print(f"Uploading {len(documents)} objects to S3 ...")

        for number, document in enumerate(
            documents,
            start=1,
        ):
            s3.put_object(
                Bucket=resources["bucket"],
                Key=document["object_key"],
                Body=build_synthetic_payload(document),
                ContentType=document["content_type"],
            )

            if number % 100 == 0:
                print(f"  uploaded {number} objects ...")

        print("S3 uploads complete.")

    # document_state=None means "state not yet known"; DynamoDB
    # items simply omit the attribute, which the aggregator and
    # the optimizer adapter read back as None.
    document_items = []

    for document in documents:
        item = dict(document)

        if item.get("document_state") is None:
            del item["document_state"]

        document_items.append(item)

    print(
        f"Writing {len(document_items)} items to "
        f"{resources['documents_table']} ..."
    )

    with documents_table.batch_writer() as batch:
        for item in document_items:
            batch.put_item(Item=item)

    print(
        f"Writing {len(events)} events to "
        f"{resources['access_history_table']} ..."
    )

    with access_history_table.batch_writer() as batch:
        for event in events:
            batch.put_item(Item=event)

    print("Load complete.")
    print(
        f"Loaded {len(document_items)} documents and "
        f"{len(events)} access events."
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(1)